import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ModalProvider } from "@/commons/providers/modal/modal.provider";
import { ThemeProvider } from "@/commons/providers/next-themes/next-themes.provider";
import { ReactQueryProvider } from "@/commons/providers/react-query/react-query.provider";
import Layout from "@/commons/layout";

const pretendard = localFont({
  src: "./fonts/PretendardVariable.woff2",
  variable: "--font-pretendard",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body
        className={`${pretendard.variable} antialiased`}
      >
        <ReactQueryProvider>
          <ThemeProvider>
            <ModalProvider>
              <Layout>
                {children}
              </Layout>
            </ModalProvider>
          </ThemeProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
