import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ModalProvider } from "@/commons/providers/modal/modal.provider";
import { ThemeProvider } from "@/commons/providers/next-themes/next-themes.provider";
import { ReactQueryProvider } from "@/commons/providers/react-query/react-query.provider";
import { ApolloClientProviderWrapper } from "@/commons/providers/apollo-client/apollo-client.provider";
import { AuthProvider } from "@/commons/providers/auth/auth.provider";
import Layout from "@/commons/layout";

const pretendard = localFont({
  src: [
    {
      path: "./fonts/Pretendard-Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/Pretendard-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Pretendard-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/Pretendard-SemiBold.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/Pretendard-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body
        className={`${pretendard.variable} antialiased`}
      >
        <AuthProvider>
          <ApolloClientProviderWrapper>
            <ReactQueryProvider>
              <ThemeProvider>
                <ModalProvider>
                  <Layout>
                    {children}
                  </Layout>
                </ModalProvider>
              </ThemeProvider>
            </ReactQueryProvider>
          </ApolloClientProviderWrapper>
        </AuthProvider>
      </body>
    </html>
  );
}
